# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1431, 751))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1429, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.table_contacts = QtWidgets.QTableView(parent=self.scrollAreaWidgetContents)
        self.table_contacts.setGeometry(QtCore.QRect(110, 10, 1200, 721))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_contacts.sizePolicy().hasHeightForWidth())
        self.table_contacts.setSizePolicy(sizePolicy)
        self.table_contacts.setMaximumSize(QtCore.QSize(1200, 16777215))
        self.table_contacts.setMouseTracking(True)
        self.table_contacts.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.table_contacts.setAcceptDrops(True)
        self.table_contacts.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.table_contacts.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AllEditTriggers)
        self.table_contacts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_contacts.setSortingEnabled(True)
        self.table_contacts.setWordWrap(True)
        self.table_contacts.setObjectName("table_contacts")
        self.table_contacts.horizontalHeader().setSortIndicatorShown(False)
        self.table_contacts.verticalHeader().setSortIndicatorShown(True)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.all_but = QtWidgets.QPushButton(parent=self.centralwidget)
        self.all_but.setGeometry(QtCore.QRect(320, 760, 100, 61))
        self.all_but.setObjectName("all_but")
        self.add_but = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_but.setGeometry(QtCore.QRect(430, 760, 100, 61))
        self.add_but.setObjectName("add_but")
        self.del_but = QtWidgets.QPushButton(parent=self.centralwidget)
        self.del_but.setGeometry(QtCore.QRect(540, 760, 100, 61))
        self.del_but.setObjectName("del_but")
        self.red_but = QtWidgets.QPushButton(parent=self.centralwidget)
        self.red_but.setGeometry(QtCore.QRect(650, 760, 100, 61))
        self.red_but.setObjectName("red_but")
        self.fnd_but = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fnd_but.setGeometry(QtCore.QRect(760, 760, 100, 61))
        self.fnd_but.setObjectName("fnd_but")
        self.hlp_but = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hlp_but.setGeometry(QtCore.QRect(1000, 760, 100, 61))
        self.hlp_but.setObjectName("hlp_but")
        self.fnd_but_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fnd_but_2.setGeometry(QtCore.QRect(880, 760, 100, 61))
        self.fnd_but_2.setObjectName("fnd_but_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.all_but.setText(_translate("MainWindow", "Вывести \n"
"список"))
        self.add_but.setText(_translate("MainWindow", "Добавить \n"
"заметку"))
        self.del_but.setText(_translate("MainWindow", "Удалить \n"
"заметку"))
        self.red_but.setText(_translate("MainWindow", "Изменить \n"
" заметку"))
        self.fnd_but.setText(_translate("MainWindow", "Поиск \n"
" заметки"))
        self.hlp_but.setText(_translate("MainWindow", "Помощь"))
        self.fnd_but_2.setText(_translate("MainWindow", "Фильтр \n"
" по дате"))
